In [6]:
import numpy as np
import pandas as pd
import category_encoders as ce

In [3]:
frame = pd.read_csv("C:\\Users\\talk2_000\\Desktop\\Python\\DatasetFiles\\CarPricePrediction\\train.csv")
frame01 = pd.read_csv("C:\\Users\\talk2_000\\Desktop\\Python\\DatasetFiles\\CarPricePrediction\\test.csv")

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [7]:
encoder_count = ce.CountEncoder(cols = ['Manufacturer' , 'Model' , 'Color' , 'Doors' ] , handle_unknown = 1)
df1 = encoder_count.fit_transform(frame)

In [8]:
df1

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,982,173,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,18332,Left wheel,3792,12
1,44731507,16621,1018,1069,23,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,18332,Left wheel,5033,8
2,45774419,8467,-,977,446,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,18332,Right-hand drive,5033,2
3,45769185,3607,862,1111,149,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,18332,Left wheel,4489,0
4,45809263,11726,446,977,446,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,18332,Left wheel,3792,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19232,45798355,8467,-,2076,8,1999,Coupe,Yes,CNG,2.0 Turbo,300000 km,4.0,Manual,Rear,777,Left wheel,3792,5
19233,45778856,15681,831,3769,1079,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,18332,Left wheel,639,8
19234,45804997,26108,836,3769,429,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,18332,Left wheel,2375,4
19235,45793526,5331,1288,1069,140,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,18332,Left wheel,5033,4
19236,45813273,470,753,3769,1079,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,18332,Left wheel,4489,12

In [11]:
df1["Manufacturer"].value_counts()

3769    3769
3662    3662
2076    2076
1111    1111
1069    1069
1049    1049
982      982
977      977
660      660
579      579
441      441
421      421
397      397
289      289
275      275
255      255
183      183
91       182
138      138
48        96
78        78
76        76
54        54
49        49
15        45
42        42
37        37
30        30
26        26
12        24
4         20
20        20
19        19
17        17
16        16
2         14
14        14
13        13
9          9
1          8
7          7
5          5
3          3
Name: Manufacturer, dtype: int64

In [12]:
frame["Manufacturer"].value_counts()

HYUNDAI          3769
TOYOTA           3662
MERCEDES-BENZ    2076
FORD             1111
CHEVROLET        1069
                 ...
SATURN              1
HAVAL               1
LANCIA              1
TESLA               1
PONTIAC             1
Name: Manufacturer, Length: 65, dtype: int64